### ISSUE TITLE
Java enums

### ISSUE THREAD

**Issue by eugene-yao-zocdoc** [vsapronov/gopoetry#1]
Greetings @vsapronov,

I'm looking to complete our scala code gen work and one thing we'd like to do is generate java enums for scala. I was wondering if you had a timeline planned for it.

**Comment by vsapronov** [comment]
I will come back to you on this on Monday. I'm currently considering to support enums in Scala based on sealed trait approach with some Jackson plugin for automatic (de)serialization of such enums.
Since there's no Java on gopetry yet. It's more about supporting Java at all then just enums support...

**Comment by eugene-yao-zocdoc** [comment]
@vsapronov poke?

**Comment by vsapronov** [comment]
Hi @eugene-yao-zocdoc  I know you implemented Java yourself. That is great!

Just wanted to give you heads up about what worked better for enums. In latest code generation we have used Scala circe for JSON (de)serialization and enumeratum for enums. Enumeratum has support for circe (when enum is a field of some Scala class being serialized with circe). Here's you can see some tests for circe and enumeratum specifically: https://github.com/ModaOperandi/spec-scala/blob/master/spec-circe/src/test/scala/EnumSpec.scala
circe has a few advantages over jackson-scala. For example it does not have type erasure issues as it's using shapeless and implicit encoders/decoders. It supports case class fields default values.

Though having Java does not hurt. If you added it to do enums in Scala generated code I would seriously consider using enumeratum or even switching to circe.
